### ISSUE TITLE
Exception in edge case (preseason, double shifts...)

### ISSUE THREAD

**Issue by jmmyerz** [jmmyerz/rides-bot#2]
When the day is split into 2 management shifts, but both managers on are scheduled for a double, the shift logic appears to break.

```
[debug] Running filter managers (684791887)
[debug] Running filter assistants (681872273)
[debug] Running filter coords (454283376)
[debug] Filtered shifts:
{
  "managers_on": [
    {
      "employee": "Kasie Wegener",
      "start_time": "08:00",
      "end_time": "18:00",
      "total_hours": 10.0,
      "description": "Manager taking calls 8:00a - 2:00p",
      "meta": {
        "is_am_shift": true,
        "is_pm_shift": true,
        "is_double_shift": true,
        "is_manager_on": true,
        "is_second_manager": false,
        "is_north_south_coord": false,
        "manager_on_times": {
          "start_time": "08:00",
          "end_time": "18:00"
        }
      }
    },
    {
      "employee": "Sid Green",
      "start_time": "07:45",
      "end_time": "19:00",
      "total_hours": 11.25,
      "description": "Manager taking calls 2:00p - 6:00p",
      "meta": {
        "is_am_shift": true,
        "is_pm_shift": true,
        "is_double_shift": true,
        "is_manager_on": true,
        "is_second_manager": false,
        "is_north_south_coord": false,
        "manager_on_times": {
          "start_time": "07:45",
          "end_time": "19:00"
        }
      }
    }
  ],
  "second_managers": [],
  "north_coords": [],
  "south_coords": []
}
[debug] Running manager on for meta shift 0
[debug] Kasie Wegener score: 200
[debug] Sid Green score: 200
[debug] Running second manager for meta shift 0
[debug] Running north coord for meta shift 0
[debug] Running south coord for meta shift 0
[debug] Running manager on for meta shift 1
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/var/www/jordanmyers.me/rides-bot/rides_bot/app.py", line 264, in <module>
    run_bot(utils.cmdline.get_args())
  File "/var/www/jordanmyers.me/rides-bot/rides_bot/app.py", line 81, in run_bot
    meta_shift['shift_times']['start'],
    ~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'shift_times'
```

**Comment by jmmyerz** [comment]
Either this is resolved or I can't be bothered to care any more
